instrument initializeUnorderedBulkOp, initializeOrderedBulkOp in mong…
newrelic/node-newrelic pull request #1111
Opened 2022-03-02 20:24 UTC by dlants

…odb v3

## Proposed Release Notes

Adds support for initializeUnorderedBulkOp, initializeOrderedBulkOp in mongodb v3 instrumentation.

## Links

## Details
I needed this monitoring for assessing load on our mongodb instance. Figured others could use it and maybe extend it to other versions of mongodb. I think it's a pretty essential feature that's currently missing from the driver.

2022-03-02 20:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=1111) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=1111) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/node-newrelic?pullRequest=1111) it.</sub>

2022-03-03 15:32 UTC, dlants commented
Hm. It seems like this implementation is not quite right. Even though the op is appearing correctly in the transaction breakdown and the database operations table, I do not see it in the histogram, and selecting it from the operations table shows "undefined undefined undefined" 
<img width="352" alt="Screen Shot 2022-03-03 at 9 42 25 AM" src="https://user-images.githubusercontent.com/1186977/156596531-bc1111b4-71c4-4cab-9b6b-fefbddcd3484.png">

2022-03-03 15:35 UTC, bizob2828 requested changes
Hi @dlants, thanks for the contribution!  A few tiny comments but overall looks great!

Also, it looks like you have some linting errors.  There is a lot of noise with warnings that you can ignore but seems like you didn't have our dev deps installed as husky should've picked up staged changes and ran linting via lint-staged.  To fix this you can just run 

```sh
npx eslint --fix lib/instrumentation/mongodb/common.js
```

2022-03-03 15:35 UTC, bizob2828 commented on lib/instrumentation/mongodb/common.js
> + * Sets up the desc for all instrumented query methods
```suggestion
 * Sets up the desc for all instrumented bulk operations
```

2022-03-03 15:35 UTC, bizob2828 commented on lib/instrumentation/mongodb/common.js
> +common.makeBulkDescFunc = function makeBulkDescFunc(shim, methodName) {
the 2nd arg on this function is unused can be removed

2022-03-03 15:37 UTC, bizob2828 commented on test/versioned/mongodb/bulk.tap.ts
> +common.test('unorderedBulkOp', function unorderedBulkOpTest(t, collection, verify) {
this is one of the rough edges of our versioned tests but you need to add bulk.tap.js to the files array in `test/versioned/mongodb/package.json`. also these tests need to be semver gated to only run on v3

2022-03-03 15:39 UTC, bizob2828 commented on test/versioned/mongodb/bulk.tap.ts
> +common.test('unorderedBulkOp', function unorderedBulkOpTest(t, collection, verify) {
```if(semver.satisfies(mongoPackage.version, '<4')) {```

2022-03-03 15:54 UTC, bizob2828 commented
> Hm. It seems like this implementation is not quite right. Even though the op is appearing correctly in the transaction breakdown and the database operations table, I do not see it in the histogram, and selecting it from the operations table shows "undefined undefined undefined" <img alt="Screen Shot 2022-03-03 at 9 42 25 AM" width="352" src="https://user-images.githubusercontent.com/1186977/156596531-bc1111b4-71c4-4cab-9b6b-fefbddcd3484.png">

Ah ok.  Admittedly I just looked at the code.  But it also does look like the versioned tests you wrote do work.  A quick way to test just that file is to do this

```
cd test/versioned/mongodb
npm i mongodb@3 --no-save --no-package-lock
node bulk.tap.js
```

Also if you want to confirm the tests run against all v3 versions of mongo you can do this

```
npm run versioned mongodb
```

2022-03-03 15:56 UTC, bizob2828 commented on test/versioned/mongodb/bulk.tap.ts
> +'use strict'
can you rename this to .js.  This doesn't contain any typescript

2022-03-03 17:05 UTC, dlants commented
> please log a ticket.
I think this is an issue with the one.newrelic.com web client, not the node agent. What's the best way to file an issue for that?

2022-03-07 16:58 UTC, bizob2828 commented
> > please log a ticket.
> 
> I think this is an issue with the one.newrelic.com web client, not the node agent. What's the best way to file an issue for that?

If you can provide a repo case I can let the UI team know as I don't think that code is open source.

2022-03-07 17:10 UTC, bizob2828 requested changes
It looks like this will fail on certain versions of mongodb 3.x.  Our CI will only run on the latest version for every major version line.  If you run 

```
npm run versioned mongodb
```

You can see the failure or you can just do this in `test/versioned/mongodb`

```
npm i mongodb@3.1.13 --no-save --no-package-lock
node bulk.tap.js
```

2022-03-07 17:30 UTC, dlants commented
>  If you can provide a repro case I can let the UI team know as I don't think that code is open source.

I wrote up the bug here: https://discuss.newrelic.com/t/bug-when-selecting-db-operations-from-db-operations-table/178575 If you could make it more visible to the UI team, that would be great.

2022-03-11 18:39 UTC, bizob2828 commented
@dlants I triaged the failure and it appears to be broken up until 3.2.4.  Since those releases are almost 3 years old I'm going to update the semver guard. I think the [fix was here](https://github.com/mongodb/node-mongodb-native/commit/f548bd7).  I also plan on filing a follow up to get this support in 4.x. It looks like it works up until 4.1.4

2022-03-11 18:42 UTC, bizob2828 commented
Actually I can't push to your remote.  Here's the diff that will fix the problem I was describing https://github.com/newrelic/node-newrelic/commit/a6c9e597372c37a370ad8ed1c90e43204139de3f

2022-03-15 12:12 UTC, bizob2828 commented
Logged https://github.com/newrelic/node-newrelic/issues/1122 to get feature parity in v4 of the mongo instrumentation

2022-03-15 12:13 UTC, bizob2828 approved these changes
Looks great.  Again, thanks for your contribution @dlants !

2022-03-15 12:38 UTC, merged