Removed certificate bundle
newrelic/node-newrelic pull request #1293
Opened 2022-07-21 20:18 UTC by bizob2828

## Proposed Release Notes
 * **BREAKING**: Removed certificate bundle from agent.  The configuration value `config.feature_flag.certificate_bundle` will no longer work.

## Links
 * Closes https://issues.newrelic.com/browse/NR-33407

## Details

2022-07-21 21:15 UTC, michaelgoin commented
We may want to add more flavoring to the release note. Maybe something similar to the following, which is largely copied from the deprecation warning:

 * **BREAKING**: Removed certificate bundle from agent. The configuration value `config.feature_flag.certificate_bundle` will no longer work.

   The agent no-longer includes the New Relic certificate bundle when using the 'certificates' configuration (commonly with proxies). If you find this breaking your current environment, we recommend getting a CA bundle such as the one from Mozilla.

2022-07-29 18:45 UTC, mrickard approved these changes

2022-07-29 18:45 UTC, michaelgoin requested changes
I believe `ca-gen.js` and `update-ca-bundle.sh` can be removed along with relevant references in `package.json`, unless I misunderstanding their usage.

2022-07-29 21:11 UTC, michaelgoin approved these changes

2022-07-29 21:11 UTC, merged