config index fix
newrelic/node-newrelic pull request #1417
Opened 2022-11-15 21:59 UTC by bizob2828

- WIP: reduced complexity for 1 function, fixed all the jsdoc warnings
- NEWRELIC-5278 refactored parts of lib/config/index.js to be less complex essentially by breaking the functions down further

## Proposed Release Notes

## Links
Closes NEWRELIC-5278

## Details
Extracted pieces of logic into their own functions to make certain functions less complex.  I also bumped our `ecmaVersion` in eslint to 2020 as Node.js 14 is 95% compliant. The only thing it does not support is [spread parameters after optional chaining](https://github.com/tc39/proposal-optional-chaining/issues/55). I think we will be safe but I can dig into specifically not allowing this.

2022-11-15 22:01 UTC, bizob2828 commented on lib/config/index.js
> +  /* eslint-disable-next-line sonarjs/max-switch-cases */
this would take a significant refactor so I disabled this rule

2022-11-16 20:16 UTC, jmartin4563 requested changes
Small nit about one of the jsdocs. Also, can we log a ticket to bump up the branch coverage here? Seems like we would want tests on some of the defaulting behaviors that currently aren't covered.

2022-11-17 14:06 UTC, bizob2828 commented
> Small nit about one of the jsdocs. Also, can we log a ticket to bump up the branch coverage here? Seems like we would want tests on some of the defaulting behaviors that currently aren't covered.

Done: https://issues.newrelic.com/browse/NEWRELIC-5406

2022-11-17 14:27 UTC, jmartin4563 approved these changes

2022-11-17 16:10 UTC, jmartin4563 approved these changes

2022-11-17 16:23 UTC, merged