NEWRELIC-6211: (winston) also instrument winston.loggers.add
newrelic/node-newrelic pull request #1480
Opened 2023-01-17 20:55 UTC by jordigh

There is a different part of the Winston API that our current instrumentation simply misses. It's possible to create a logger by directly calling `createLogger`, but it's also possible to add new loggers to the list of loggers by doing `winston.loggers.add` with almost the same syntax.

This factors out a bit of the logic so that both methods of creating winston loggers are instrumented.

## Proposed Release Notes

* Instrument `winston.loggers.add` so it works like `winston.createLoggers`.

## Links

* Closes NEWRELIC-6211

2023-01-18 22:13 UTC, jmartin4563 requested changes
Comment about the supportability metric move

2023-01-19 14:40 UTC, jordigh commented on lib/instrumentation/winston.js
> +  createModuleUsageMetric('winston', agent.metrics)
Right, so I reasoned that the real instrumentation was whenever `createLogger`/`loggers.add` was instrumented, i.e. during `require`, whether it was called with stream options or not. I deliberately created a test that if you created two loggers, one with each method, we would only record a single instrumentation.

Do you think that's the wrong idea? If for some reason someone calls both `createLogger` and `loggers.add`, should we count that as two instrumentations in our metrics?

2023-01-19 18:13 UTC, bizob2828 commented on lib/instrumentation/winston.js
> +  createModuleUsageMetric('winston', agent.metrics)
Yea I think this has to move back into instrumentation.  Per the spec

> Supportability/Logging/{language}/{framework}/{enabled\|disabled}`|**MUST** be generated by agents when instrumentation is installed for application logging. `disabled` **SHOULD*      * be generated if possible, although some agents' implementation may preclude it. This metric does not take the enabled/disabled state of individual features (i.e. metrics, forward      ing) into account. It is expected to be sent once per agent connect (not per harvest). `framework` names are at the discretion of the language agent teams.

2023-01-19 19:01 UTC, jordigh commented on lib/instrumentation/winston.js
> +  createModuleUsageMetric('winston', agent.metrics)
Okay, changed.

2023-01-20 15:07 UTC, jmartin4563 approved these changes

2023-01-20 16:10 UTC, merged