fix: Replace request.abort with response.close in HTTP instrumentation
newrelic/node-newrelic pull request #1510
Opened 2023-02-16 22:14 UTC by jmartin4563

## Proposed Release Notes
* fix: Replace `request.abort with `response.close` in HTTP instrumentation

## Links
* Fixes NR-88357
* https://github.com/nodejs/node/issues/40775
* https://github.com/nodejs/node/pull/33035
* https://nodejs.org/dist/latest-v16.x/docs/api/deprecations.html#DEP0156

## Details
In Node.js 16, there was a breaking change where request.aborted will no longer be emitted by the HTTP Node core. Instead, we will now rely on response.close, which works in all currently supported versioned of node (14/16/18)

2023-02-17 19:03 UTC, bizob2828 requested changes

2023-02-17 19:03 UTC, bizob2828 commented on lib/instrumentation/core/http.js
>      response.once('finish', instrumentedFinish)
I don't think we need finish since close happens after finish

2023-02-17 19:03 UTC, bizob2828 commented on test/versioned/express/helpers/request.js
> +  axios
we spoke offline to rely on native http.request instead of axios

2023-02-17 21:26 UTC, jmartin4563 commented on test/versioned/express/helpers/request.js
> +// Polyfill till we drop support for Node 14
I actually replaced the abort controller with request.destroy, so no need to use the abort controller anymore

2023-02-21 16:49 UTC, bizob2828 approved these changes

2023-02-21 16:49 UTC, merged