NEWRELIC-6962: add versioned tests to community Prisma PR
newrelic/node-newrelic pull request #1522
Opened 2023-03-01 22:57 UTC by jordigh

## Proposed Release Notes

* Added versioned tests for community Prisma PR

## Links

* NEWRELIC-6962

## Details

* Small change to the raw queries, changing the order of the name to ensure the table name comes before the operation, as per the agent metrics spec.

2023-03-02 21:26 UTC, bizob2828 requested changes
I was comparing the pg versioned tests and we are missing tests around slow queries.  However, our instrumentation does not currently support this so I will log a different ticket and address that now.  Overall this looks fine just suggested we add more raw queries to be sure we don't regress in future

2023-03-02 21:28 UTC, jordigh commented on test/versioned/prisma/prisma.tap.js
> +      prisma.$queryRaw`SELECT * FROM "public"."User"`,
okok will write more tests

2023-03-02 22:50 UTC, jordigh commented on test/versioned/prisma/prisma.tap.js
> +      prisma.$queryRaw`SELECT * FROM "public"."User"`,
Okay done

2023-03-03 14:51 UTC, bizob2828 commented on lib/instrumentation/@prisma/client.js
> +      query = args[0].args[0]
glad i asked you to do this 🎉

2023-03-03 14:51 UTC, bizob2828 approved these changes

2023-03-03 14:51 UTC, merged