feat: update support statement
newrelic/node-newrelic pull request #1733
Opened 2023-07-20 18:34 UTC by bradleycamacho

This updates the support statement to standardize on other release not formats. 

See my conversation w/ @mrickard in `#node-agent` for more info

2023-07-20 18:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=1733) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=1733) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/node-newrelic?pullRequest=1733) it.</sub>

2023-07-20 18:39 UTC, bizob2828 requested changes

2023-07-20 18:39 UTC, bizob2828 commented on bin/create-docs-pr.js
> +We recommend updating to the latest agent version as soon as it's available. If you can't upgrade to the latest version, update your agents to a version no more than 90 days old. Read more about keep
You also have to update `bin/create-github-release.js`

2023-07-21 14:40 UTC, jmartin4563 commented on bin/create-docs-pr.js
> +See the New Relic Ruby agent EOL policy for information about agent releases and support dates. (https://docs.newrelic.com/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy/)`
```suggestion
See the New Relic Node.js agent EOL policy for information about agent releases and support dates. (https://docs.newrelic.com/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy/)`
```

2023-07-26 17:02 UTC, bizob2828 approved these changes

2023-07-26 17:03 UTC, merged