DO NOT MERGE - feat: Updated agent to use require-in-the-middle to register CommonJS instrumentation
newrelic/node-newrelic pull request #1758
Opened 2023-08-11 19:53 UTC by bizob2828

## Description

This is just getting opened for the team to take a look.  The external versioned tests will fail because `@newrelic/test-utilities` needs to be updated and merged.  I guess I could just make it backwards compatible, I may look into this.  Aside from that any of the ESM tests will now fail, I plan on layering on another change the uses `import-in-the-middle`.  

To test locally
 1. In `node-test-utilities`: `git checkout ritm-updates && npm ci && npm link`
 2. In a local checkout of this branch `npm ci && npm link @newrelic/test-utilities`
 3. `npm run versioned:major`. You should only see esm failures.

2023-08-16 16:23 UTC, mrickard approved these changes

2023-08-16 19:43 UTC, jmartin4563 requested changes
I'm also concerned about how `instrumentLoadedModule` will work with this and the registering of multiple instrumentations. Additionally have we checked that the security agent works with all this stil?

2023-08-16 20:19 UTC, bizob2828 commented on test/versioned/express-esm/package.json
> +        "node": "<=16.12.0"
This is done only in this branch to get a green CI. The iitm branch restores this

2023-08-16 20:19 UTC, bizob2828 commented on lib/shimmer.js
> -      NAMES.FEATURES.INSTRUMENTATION.ON_RESOLVED
Correct I have it on my list to queue up

2023-08-16 20:20 UTC, bizob2828 commented
> I'm also concerned about how `instrumentLoadedModule` will work with this and the registering of multiple instrumentations. Additionally have we checked that the security agent works with all this still? _ducks to avoid flying objects_

I don't have any of those concerns as those interactions are a layer above. I can double check them though.

2023-08-16 20:56 UTC, bizob2828 commented on lib/shimmer.js
> -      NAMES.FEATURES.INSTRUMENTATION.ON_RESOLVED
https://source.datanerd.us/agents/angler/pull/476

2023-08-16 21:12 UTC, bizob2828 commented
Ran security agent on node 18 and 20 both clean runs.  Here's a snippet of output

```sh
===============================================================
PASS

real	4m36.526s
user	11m45.966s
sys	3m13.235s
      276.98 real       705.96 user       193.24 sys
```

2023-08-17 15:23 UTC, bizob2828 commented
instrumentLoadedModule just works: https://staging.onenr.io/09MR2ozAkjY

```js
const express = require('express')
const newrelic = require('newrelic')
newrelic.instrumentLoadedModule('express', express) 
const app = express()
const { PORT = 3000 } = process.env
const lib = require('@aws-sdk/client-sns')
const sns = new lib.SNSClient()

app.get('/named-route', (req, res) => {
  res.send('hi')
})

app.get('/sns', async (req, res) => {
  const cmd = new lib.ListTopicsCommand({})
  const result = await sns.send(cmd)
  res.send(result)

})

app.listen(PORT, () => console.log(`Example app listening on port ${PORT}!`))

````

I'm going to check ESM app because i have a feeling this will now work too

2023-08-17 15:32 UTC, jmartin4563 approved these changes

2023-08-17 15:35 UTC, merged