perf(Trace): use faster way to copy one array into another
newrelic/node-newrelic pull request #1780
Opened 2023-09-09 10:47 UTC by kibertoad

## Description

This is a follow-up to https://github.com/newrelic/node-newrelic/pull/1774, optimizing the solution further. This is the fastest way to copy values from one array into another array, see https://github.com/kibertoad/nodejs-benchmark-tournament/blob/master/combine-arrays/_results/results.md for benchmarking results (pushDestruct method; `destruct` or `concat` are not feasible, because we are adding values in place, not creating a new array, and currently `pushForEach` is used, which is the slowest way to do so)

This retains the same logic as is currently used, but works faster.

## How to Test

I've benchmarked the algorithm to ensure that this is the fastest possible option. See https://github.com/kibertoad/nodejs-benchmark-tournament/blob/master/combine-arrays/contestants/pushDestruct.js for how this was implemented in benchmark.

## Related Issues

https://github.com/newrelic/node-newrelic/pull/1774

2023-09-09 10:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=1780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=1780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/node-newrelic?pullRequest=1780) it.</sub>

2023-09-11 15:02 UTC, kibertoad commented
@bizob2828 ping

2023-09-11 15:19 UTC, bizob2828 approved these changes

2023-09-11 15:25 UTC, bizob2828 commented
@kibertoad you'll have to rebase.  There was an unrelated test fix for pino 8.15.1. that I just landed in #1782

2023-09-11 15:25 UTC, kibertoad commented
@bizob2828 It's not possible to rebase on merge?

2023-09-11 15:31 UTC, bizob2828 commented on lib/transaction/trace/index.js
> +    segments.push(...segment.getChildren())
It looks like we have a test that creates a lot of child segments and then contains stacks.  This test is now failing by spreading the children and pushing vs iterating and pushing

2023-09-11 15:34 UTC, bizob2828 requested changes
Although this is faster it appears there are historical reason why it is iterating and pushing

2023-09-11 15:39 UTC, kibertoad commented
Right, so this PR should be adjusted to just use the for loop?

2023-09-13 16:58 UTC, kibertoad commented
@bizob2828 Yeah, that was my thought. Should we do that, or should we just close this PR?

2023-09-13 17:05 UTC, bizob2828 commented
> @bizob2828 Yeah, that was my thought. Should we do that, or should we just close this PR?

It's up to you. Honestly, the initial PR was the first time I ever looked at this code.  It's very old and thankfully we have some integration tests to expose the nuance that you hit.

2023-10-11 14:05 UTC, bizob2828 commented
I'm going to close this since there's been 0 activity for a month. Feel free to reopen with my suggestions addressed.

2023-10-11 14:05 UTC, closed without merging