chore(deps): Updated @newrelic/security agent to v1.0.1
newrelic/node-newrelic pull request #2002
Opened 2024-02-07 17:21 UTC by bizob2828

## Description

* Updated @newrelic/security-agent to v1.0.1

### v1.0.1 (2024-02-07)
#### Bug fixes
* Reporting of framework in security event json 
#### Miscellaneous chores
* Updated software license to New Relic Software License Version 1.0
* Ability to send critical messages on successful startup of agent
* Updated Copyright headers
* Updated license in readme

## How to Test

`npm run versioned:security`

2024-02-07 17:26 UTC, mrickard submitted a review, later dismissed

2024-02-07 17:35 UTC, jsumners-nr requested changes
I think we need an answer regarding where the license came from before we merge it. This line is particularly troubling:

https://github.com/newrelic/csec-node-agent/blob/1264369b51efc5d1ff2fa465f7f4f69861826061/LICENSE#L13

I read that as saying no one can use the `newrelic` module after this is merged unless they have a paid subscription. I do believe we support free tier users?

2024-02-09 02:04 UTC, toobagrrl commented
Approved NR Legal

2024-02-09 12:43 UTC, jsumners-nr approved these changes

2024-02-09 14:46 UTC, merged