chore: Migrated superagent instrumentation into core module
newrelic/node-newrelic pull request #2141
Opened 2024-04-11 19:49 UTC by jsumners-nr

This PR resolves #2128.

2024-04-11 19:58 UTC, jsumners-nr commented on lib/instrumentations.js
>    return {
I sorted the lines in these objects. I find it a lot easier to read names in alphabetical order, and to figure out where to add a new item when the list is in alphabetical order.

2024-04-12 20:17 UTC, bizob2828 requested changes
A few small things, but overall looking good.

You'll need to remove superagent from [external repos](https://github.com/newrelic/node-newrelic/blob/main/test/versioned-external/external-repos.js#L31)

we will probably have to have a separate story to archive the old repo and deprecate `@newrelic/superagent`

2024-04-12 20:17 UTC, bizob2828 commented on lib/instrumentation/superagent/nr-hooks.js
> +    moduleName: 'superagent',
you don't need this. you can just have `lib/instrumentation/superagent.js`. the nr-hooks is designed when you have packages you're instrumenting that have more than once package, etc

2024-04-12 20:17 UTC, bizob2828 commented on lib/instrumentation/superagent/lib/http-methods.js
> +const http = require('http')
you could also just fold this into the `lib/instrumentation/superagent.js`

2024-04-12 20:17 UTC, bizob2828 commented on package.json
>      "should": "*",
you should remove `@newrelic/superagent`

2024-04-15 14:58 UTC, bizob2828 approved these changes

2024-04-15 16:18 UTC, merged