chore: Removed package-lock.json
newrelic/node-newrelic pull request #2208
Opened 2024-05-22 18:00 UTC by jsumners-nr

As we discussed prior to stand-up on 2024-05-22, this PR removes the `package-lock.json` from this repo. Doing so provides:

1. No more useless Dependabot updates that change items in the lock file: when people `npm install newrelic`, the lock file does not get consulted and thus none of the Dependabot changes have any affect on our customers.
2. Easier detection of dependency updates in workflows. This will allows #2205 to be updated in such a fashion that we can detect changes to dependency blocks in `package.json` so that test suites can be triggered or skipped accordingly. With the lock file in place, this sort of workflow detection will be very difficult.

2024-05-22 18:03 UTC, jsumners-nr commented on .github/workflows/release-creation.yml
> +        npm install
The only concern I have in this PR is this line. I do not expect any problem as `npm install` should still install all dependencies. The difference would be if a repo that is reusing this workflow has updates to `package.json` and _not_ `package-lock.json`. In that case, `npm ci` would notice the discrepancy and generate an error. Whereas `npm install` will install the dependencies as noted by `package.json`.

2024-05-23 12:44 UTC, bizob2828 requested changes
I think we should add package-lock.json to .gitignore to be safe. I know you set it in npmignore but wouldn't hurt.

2024-05-23 12:46 UTC, jsumners-nr commented
> I think we should add package-lock.json to .gitignore to be safe. I know you set it in npmignore but wouldn't hurt.

Good call. Done.

2024-05-23 12:57 UTC, bizob2828 approved these changes

2024-05-23 13:01 UTC, merged