chore: Added AI support docs for automation
newrelic/node-newrelic pull request #2249
Opened 2024-06-05 14:47 UTC by jsumners-nr

The purpose of this PR is to add a JSON file we can utilize in our docs automation to add documentation around which "AI" things we support, and how deep that support goes for each thing. I have not started on the automation yet. So this is subject to change, but I believe it will satisfy our immediate needs.

2024-06-10 16:57 UTC, mrickard approved these changes

2024-06-11 15:58 UTC, bizob2828 requested changes

2024-06-11 15:58 UTC, bizob2828 commented on ai-support.json
> +        "name": "Claude",
I would add the vendor too. `Anthropic Claude`

2024-06-11 15:58 UTC, bizob2828 commented on ai-support.json
> +        "name": "Jurassic-2",
`AI21 Labs Jurassic-2`

2024-06-11 15:58 UTC, bizob2828 commented on ai-support.json
> +        "name": "Llama2",
`Meta Llama 2`

2024-06-11 15:58 UTC, bizob2828 commented on ai-support.json
> +        "name": "Titan",
`Amazon Titan`

2024-06-11 16:17 UTC, bizob2828 approved these changes

2024-06-11 16:19 UTC, merged