refactor: Migrated Next.js instrumentation into agent
newrelic/node-newrelic pull request #2409
Opened 2024-07-30 18:27 UTC by bizob2828

## Description

This did a repo migration and retained all commit history.  When we merge this PR we cannot squash and merge. 

## How to Test

## Related Issues
Closes #2127

2024-07-30 18:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2409) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2409) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: svetlanabrennan<br/>:x: alissonsleal<br/><hr/>**svetlanabrennan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/node-newrelic?pullRequest=2409) it.</sub>

2024-07-30 19:39 UTC, jsumners-nr requested changes

2024-07-30 19:39 UTC, jsumners-nr commented on merged/nextjs/README.md
Looks like a `merged/` directory has made it into the change set.

2024-07-30 19:49 UTC, bizob2828 commented on merged/nextjs/README.md
Forgot to cleanup once I migrated all relevant work. Also served as a reminder to dig into the old index.js. I'll take a look

2024-07-31 11:40 UTC, jsumners-nr approved these changes

2024-07-31 13:57 UTC, merged