Fix inline require causes performance issues
newrelic/node-newrelic pull request #2506
Opened 2024-08-20 20:23 UTC by trenton05

## Description

Please provide a brief description of the changes introduced in this pull request.
What problem does it solve? What is the context of this change?

The combination of code-level-metrics require('@contrast/fn-inspect') with @newrelic/ritm being hooked into requires causes a cascading load issue for nodejs.

## How to Test

Please describe how you have tested these changes. Have you run the code against an example application?
What steps did you take to ensure that the changes are working correctly?

For reference, our express server with newrelic was taking 10 seconds to handle 500 requests.  After this change, the same 500 requests takes about half a second.  Should be able to be tested with a similar configuration.

## Related Issues

Please include any related issues or pull requests in this section, using the format `Closes #<issue number>` or `Fixes #<issue number>` if applicable.

Creating this to capture the issue and fix for the newrelic team, we have patched it locally so that we do not run across this issue anymore.

2024-08-20 20:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2506) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/node-newrelic?pullRequest=2506) it.</sub>

2024-08-20 20:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2506) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/node-newrelic?pullRequest=2506) it.</sub>

2024-08-21 14:48 UTC, bizob2828 commented
@trenton05 do you happen to have a repro case? I'd just like to dig into the root cause and see how moving requiring of `@contrast/fn-inspect` within the function solves the issue

2024-08-21 14:50 UTC, bizob2828 requested changes

2024-08-21 14:51 UTC, bizob2828 commented
@trenton05 we require conventional commits, can you please fix up your PR title at the very least because that's what we'll use on merge

2024-08-27 15:21 UTC, bizob2828 commented
@trenton05 just following up. can you please provide a repro case so we can dig into the root cause and validate that this fix will be enough?

2024-09-17 15:33 UTC, closed without merging

2024-09-17 15:39 UTC, trenton05 commented
Sorry I don't have the time to setup a test. A simple express server handling requests can easily be benchmarked. I made this PR to let your team know it was a serious issue on our end and this resolved it for us.

2024-09-17 15:47 UTC, bizob2828 commented
> Sorry I don't have the time to setup a test. A simple express server handling requests can easily be benchmarked. I made this PR to let your team know it was a serious issue on our end and this resolved it for us.

Ok i'll see if I can reproduce and follow up