feat: Added New Relic Control health check
newrelic/node-newrelic pull request #2841
Opened 2024-12-17 18:10 UTC by jsumners-nr

This PR resolves #2838.

2025-01-07 19:06 UTC, bizob2828 reviewed
i know this is in draft, just called out the lack of config items defined

2025-01-07 19:06 UTC, bizob2828 commented on lib/health-reporter.js
> +    const fleetId = process.env.NEW_RELIC_SUPERAGENT_FLEET_ID
these should be configuration items, based on spec, and names appear to be updated to be agent_control not superagent:

| Name | Environment Variable Name | Description | Default | Required? |
| --- | --- | --- | --- | -- |
| agent_control.fleet_id | NEW_RELIC_AGENT_CONTROL_FLEET_ID | This assigns a fleet ID to the language agent. This ID is generated by Agent Control. If this setting is present, it denotes that the agent is running in an Agent Control environment and the health file(s) will be generated. | n/a | MUST |
| agent_control.health.delivery_location | NEW_RELIC_AGENT_CONTROL_HEALTH_DELIVERY_LOCATION | A `file:` URI that specifies the fully qualified directory path for health file(s) to be written to. For example: `file:///var/lib/newrelic-agent_control/fleet/agents.d/<fleet_id>` | N/A | MUST |
| agent_control.health.frequency | NEW_RELIC_AGENT_CONTROL_HEALTH_FREQUENCY | The interval, in seconds, of how often the health file(s) will be written. | 5 | MUST |

2025-01-08 13:39 UTC, jsumners-nr commented on lib/health-reporter.js
> +    const fleetId = process.env.NEW_RELIC_SUPERAGENT_FLEET_ID
It looks like we _do_ load the config before creating the agent. So adding in support for those config values will be feasible.

2025-01-24 15:05 UTC, bizob2828 requested changes
I haven't completely reviewed but a few comments. Also I don't see tests for every health status. At the very least we should have already have tests for `STATUS_HEALTHY`, `STATUS_INVALID_LICENSE_KEY`, `STATUS_AGENT_DISABLED`, `STATUS_CONNECT_ERROR`

2025-01-24 15:05 UTC, bizob2828 commented on test/unit/agent/agent.test.js
> +process.env.NEW_RELIC_AGENT_CONTROL_ENABLED = 'true'
i would just set these in agent config

2025-01-24 15:05 UTC, bizob2828 commented on test/unit/config/config.test.js
> +  await t.test('loads from env', () => {
we have a separate file for env var conversion: `test/unit/config/config-env.test.js`

2025-01-24 15:05 UTC, bizob2828 commented on test/unit/config/config.test.js
> +  await t.test('loads from provided config', () => {
we have a file that also tests defaults `test/unit/config/config-defaults.test.js`

2025-01-24 16:59 UTC, jsumners-nr commented on lib/config/default.js
> +      env: 'NEW_RELIC_AGENT_CONTROL_ENABLED',
Are you suggesting to not provide default values? I don't understand the review comment.

2025-01-24 17:01 UTC, jsumners-nr commented on lib/config/default.js
> +        default: 'file:///var/lib/newrelic-agent_control/fleet'
I copied the example string, it seems.

2025-01-24 17:03 UTC, jsumners-nr commented on lib/config/default.js
> +      env: 'NEW_RELIC_AGENT_CONTROL_ENABLED',
Oh, you're saying that `{ agent_control: { enabled } }` will already be parsed from `NEW_RELIC_AGENT_CONTROL_ENABLED` regardless of setting the `env` key. I was unaware of that. Are you strongly against setting the `env` key? It is clearer to me.

2025-01-24 17:03 UTC, bizob2828 commented on lib/config/default.js
> +      env: 'NEW_RELIC_AGENT_CONTROL_ENABLED',
this key is for overrides. it'll default to what you provided so it just confuses things.  we default all env vars [here](https://github.com/newrelic/node-newrelic/blob/main/lib/config/index.js#L1120)

2025-01-24 17:04 UTC, jsumners-nr commented on lib/health-reporter.js
> +    if (outDir.includes('://') === true) {
It is covered by https://github.com/jsumners-nr/node-newrelic/blob/6accc52abc4f63a98e7a10abf25af6c2634433d0/test/unit/agent/agent.test.js#L91-L113

2025-01-24 17:05 UTC, jsumners-nr commented on test/unit/agent/agent.test.js
> +process.env.NEW_RELIC_AGENT_CONTROL_ENABLED = 'true'
These can be considered cruft from the original implementation that was environment based only. I was just too lazy to remove them.

2025-01-24 17:07 UTC, bizob2828 commented on lib/config/default.js
> +      env: 'NEW_RELIC_AGENT_CONTROL_ENABLED',
maybe we can add PR separately and rename it `envOverride` or something, or we could document the structure better

2025-01-24 17:08 UTC, jsumners-nr commented on lib/config/default.js
> +      env: 'NEW_RELIC_AGENT_CONTROL_ENABLED',
Yeah, renaming it to `envVarNameOverride` would be a lot clearer. I'll go ahead and remove them.

2025-01-24 17:08 UTC, bizob2828 commented on lib/health-reporter.js
> +    if (outDir.includes('://') === true) {
ah, i was looking in the unit tests for health reporter, my bad

2025-01-24 17:12 UTC, bizob2828 commented on lib/health-reporter.js
> +    if (outDir.includes('://') === true) {
that's because in the test you're replacing `file://` with `''`

2025-01-24 17:23 UTC, jsumners-nr commented on lib/health-reporter.js
> +    agentConfig = { agent_control: { health: {} } },
Except in testing. This default allows for easier unit testing and fewer `?.` guards.

2025-01-24 20:02 UTC, jsumners-nr commented on lib/health-reporter.js
> +    if (outDir.includes('://') === true) {
Yes, I have it covered locally.

2025-01-27 17:36 UTC, jsumners-nr commented on lib/validate-license-key.js
We did not have a key verification check. In order to validate the health status for an invalid license key, we had to add one. The result is that I had to update the key that the vast majority of the tests validate themselves against.

2025-01-31 17:59 UTC, bizob2828 reviewed
After re-reviewing spec, there are a few codes that are missing/in the wrong spot:


| code       | status                                                       | notes                                                        |
|------------|--------------------------------------------------------------|--------------------------------------------------------------|
| NR-APM-000 | Healthy                                                      | ✅                                                            |
| NR-APM-001 | Invalid license key (HTTP status code 401)                   | This occurs in `lib/collector/api`. You should be able to use `this._agent.healthReporter` to properly log these [here](https://github.com/newrelic/node-newrelic/blob/main/lib/collector/api.js#L236)     |
| NR-APM-002 | License key missing in configuration                         | ✅                                                            |
| NR-APM-003 | Forced disconnect received from New Relic (HTTP status code 410) | TThis occurs in `lib/collector/api`. You should be able to use `this._agent.healthReporter` to properly log these [here](https://github.com/newrelic/node-newrelic/blob/main/lib/collector/api.js#L233)     |
| NR-APM-004 | HTTP error response code [%s] received from New Relic while sending data type [%s] | I'm not sure on this one                                     |
| NR-APM-005 | Missing application name in agent configuration              | ✅                                                            |
| NR-APM-006 | The maximum number of configured app names (3) exceeded      | it does not appear we check for this                         |
| NR-APM-007 | HTTP Proxy configuration error; response code [%s]           | This occurs in `lib/collector/api`. You should be able to use `this._agent.healthReporter` to properly log these [here](https://github.com/newrelic/node-newrelic/blob/main/lib/collector/api.js#L244)      |
| NR-APM-008 | Agent is disabled via configuration                          | ✅                                                            |
| NR-APM-009 | Failed to connect to New Relic data collector                | I'm not sure if this is getting conflated with the 410 error above |
| NR-APM-010 | Agent config file is not able to be parsed                   | we're missing this: [node-newrelic/index.js at main · newrelic/node-newrelic](https://github.com/newrelic/node-newrelic/blob/main/index.js#L91), however I don't get this because we cannot use the health reporter until the config is parsed |
| NR-APM-099 | Agent has shutdown **SHOULD** only be reported if agent is "healthy" on shutdown | ✅                                                            |

2025-01-31 17:59 UTC, bizob2828 commented on lib/agent.js
> +  } else if (validateLicenseKey(this.config.license_key) === false) {
this state is meant for when the collector responds with a 401.  The code is [here](https://github.com/newrelic/node-newrelic/blob/main/lib/collector/api.js#L236)

```
NR-APM-001 | Invalid license key (HTTP status code 401)
```

2025-01-31 17:59 UTC, bizob2828 commented on lib/agent.js
> +  } else if (validateLicenseKey(this.config.license_key) === false) {
we should also be setting the status for the [branch above](https://github.com/newrelic/node-newrelic/blob/main/lib/collector/api.js#L233) which is a 410

```
NR-APM-003 | Forced disconnect received from New Relic (HTTP status code 410)
```

2025-01-31 18:08 UTC, bizob2828 requested changes
Looking good. I finally did a thorough pass and called out some missing status codes or they are not in the correct place

2025-01-31 18:08 UTC, bizob2828 commented on lib/health-reporter.js
> +  ['NR-APM-300', 'An unexpected error occurred.']
make sure you PR the spec to document this code

2025-01-31 18:08 UTC, bizob2828 commented on lib/validate-license-key.js
> +module.exports = function validateLicenseKey(key) {
as i mentioned in the place this is used. This is not the intent of the invalid license key code, we're relying on the response from collector to determine this. I know you went through and updated all the fake keys to something that conforms but you can undo that as well

2025-02-03 20:57 UTC, bizob2828 requested changes
One last test, asserting that we're setting the agent disabled status.  Looks like we have

```js
test('should not throw with valid config', () => {
  const config = configurator.initialize({ agent_enabled: false })
  const agent = new Agent(config)
  assert.equal(agent.config.agent_enabled, false)
})
```

2025-02-04 14:30 UTC, bizob2828 approved these changes

2025-02-04 14:39 UTC, merged