Move init container release from lambda to GHA
newrelic/node-newrelic pull request #2848
Opened 2024-12-19 00:01 UTC by hmstepanek

## Description
We are getting rid of the internal auto-layer-releases repo and moving creating of the release tags into each agent's GHA deploy flow.

2024-12-19 00:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2848) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/node-newrelic?pullRequest=2848) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/node-newrelic?pullRequest=2848) it.</sub>

2024-12-19 15:40 UTC, bizob2828 commented
@hmstepanek I know this is in draft but do you mind linking what this is replacing?

2024-12-30 20:01 UTC, jsumners-nr commented on .github/workflows/post-release.yml
> +          gh-cli-version: 2.63.2
This is already included in the base runner image https://github.com/actions/runner-images/blob/5a7153bb5202eef32ea449dc8968059ae8eed692/images/ubuntu/Ubuntu2204-Readme.md#cli-tools

2025-01-15 12:30 UTC, jsumners-nr requested changes
I'm not convinced the new job belongs in this workflow. We _will_ have occasion to run this workflow manually in order to regenerate our docs (either in the local repo, the main NR docs repo, or both). The way this new job is configured, by its `if` clause, will have it running _whenever_ this workflow is triggered. Is that desired? I have a hunch that it is not desired. I am thinking that this job deserves its own workflow.

2025-01-15 12:30 UTC, jsumners-nr commented on .github/workflows/post-release.yml
> +  release-tags:
I believe this job changes the description of the workflow on line 7, at the very least.

2025-01-23 01:53 UTC, hmstepanek commented on .github/workflows/post-release.yml
> +  release-tags:
I'm not a GHA expert so forgive me. Which line in this is causing it to override the description? Line 69 is just the name of the job so that shouldn't override the description as far as I know.
I can certainly make this it's own workflow. I can understand wanting to run the docs separately on occasion.

2025-01-23 13:23 UTC, jsumners-nr approved these changes
Looks good to me.

2025-01-24 14:43 UTC, bizob2828 commented
@hmstepanek I'm not sure why the CLA isn't auto-acknowledging you as an employee but can you sign it? Also, where is the value of the `GH_RELEASE_TOKEN`?

2025-01-27 19:57 UTC, hmstepanek commented
> @hmstepanek I'm not sure why the CLA isn't auto-acknowledging you as an employee but can you sign it? Also, where is the value of the `GH_RELEASE_TOKEN`, can you share it with our team in 1Password so we can add it to our secrets?

The value of the token is shared in the 1password agent shared credentials area as `Github token for layer and init container tags`.

2025-01-27 20:16 UTC, jsumners-nr commented
When is this supposed to be merged?

2025-01-27 20:20 UTC, bizob2828 commented
I added secret to repo

2025-01-27 20:22 UTC, bizob2828 requested changes

2025-01-27 20:22 UTC, bizob2828 commented on .github/workflows/release-lambda-init-containers.yml
> +          RELEASE_TITLE="New Relic Node Agent v${{ steps.get_tag.outputs.latest_tag }}.0"
looks like this may need to be updated based on the .net agent's teams changes [here](https://github.com/newrelic/newrelic-dotnet-agent/commit/74c0f8d9992cc9fe6d95558b6307ff96a0fdd7bf)

2025-01-27 20:24 UTC, bizob2828 commented on .github/workflows/release-lambda-init-containers.yml
> +          gh release create "${RELEASE_TAG}" --title=${RELEASE_TITLE} --repo=newrelic/newrelic-agent-init-container --notes=${RELEASE_NOTES}
```suggestion
          echo "newrelic/newrelic-lambda-layers - Releasing \"${RELEASE_TITLE}\" with tag ${RELEASE_TAG}"
          gh release create "${RELEASE_TAG}" --title="${RELEASE_TITLE}" --repo=newrelic/newrelic-lambda-layers --notes="${RELEASE_NOTES}"
          echo "newrelic/newrelic-agent-init-container - Releasing \"${RELEASE_TITLE}\" with tag ${RELEASE_TAG}"
          gh release create "${RELEASE_TAG}" --title="${RELEASE_TITLE}" --repo=newrelic/newrelic-agent-init-container --notes="${RELEASE_NOTES}"
```

2025-01-27 20:24 UTC, bizob2828 approved these changes

2025-01-27 20:39 UTC, merged