chore: Updated eslint configuration
newrelic/node-newrelic pull request #2851
Opened 2024-12-23 14:11 UTC by jsumners-nr

This PR updates the eslint configuration, and plugins, to the latest. I discovered that our shared configuration has not kept up-to-date on the packages that it uses. In particular:

1. `eslint` released v9 that radically changes (and simplifies) how configuration is written and parsed.
2. `eslint-plugin-node` has been out-of-maintenance for a long time, replaced by `eslint-plugin-n`

The result was a difficult to update shared configuration package. Now that this PR is ready, I _could_ go back and update the shared package to eslint@9 standards, but I'm not convinced the shared package is worth the maintenance cost. Most of the configuration is specific to the repository. I am quite certain that most of the packages we maintain can get by with the simple `neostandard` configuration.

2024-12-24 17:37 UTC, jsumners-nr commented on test/unit/spans/map-to-streaming-type.test.js
> +  const intValue = 999999999999999
This one generated an error about the value overflowing. I don't think we were trying to test against an overflowed value, so I just shortened it to fit.

2024-12-30 13:39 UTC, jsumners-nr commented on eslint-plugin-newrelic-header.js
The `eslint-plugin-header` module has not been maintained in several years (last real commit in 2021 wasn't even a code commit). I found it simpler to add our own extension that covers our use cases.

2025-01-02 21:28 UTC, bizob2828 requested changes
this is a very large PR, i went through most. you removed all the ignoring of the no console and it won't show this as a warning because lint is quiet but not sure if we want to restore those or not.  i also noticed now that lint is quiet there are a few tests that are using `t.diagnostic` and they should prob be removed

2025-01-02 21:28 UTC, bizob2828 commented on test/unit/api/api-instrument-loaded-module.test.js
> -      // eslint-disable-next-line node/no-missing-require
i know this switched to `eslint-plugin-n` but this still should fail, not sure what's going on here

2025-01-02 21:28 UTC, bizob2828 commented on eslint.config.js
> +    '@stylistic/space-before-function-paren': 'off'
are we going to cut a ticket to address this separately?

2025-01-02 21:28 UTC, bizob2828 commented on eslint.config.js
> +    reportUnusedDisableDirectives: 'error'
very nice

2025-01-03 14:00 UTC, jsumners-nr commented on test/unit/api/api-instrument-loaded-module.test.js
> -      // eslint-disable-next-line node/no-missing-require
The current configuration applies the `eslint-plugin-node` "recommended" rules. The configuration in this PR omits them. I experimented with adding them back in yesterday afternoon, but it flagged a whole bunch of things as not supported prior to Node 18/20. It was doing so because it thinks we are trying to target `>=16` (the finally fallback as described in https://github.com/eslint-community/eslint-plugin-n?tab=readme-ov-file#configured-nodejs-version-range).

I have implemented some tweaking of the rules for this code base and included it in my latest commit.

2025-01-03 14:02 UTC, jsumners-nr commented
> you removed all the ignoring of the no console and it won't show this as a warning because lint is quiet but not sure if we want to restore those or not.

Supposedly it was set as "warn" in the original configuration https://github.com/newrelic/eslint-config-newrelic/blob/c5780025fff0c92d6d9012e6132e84fb42ad2459/index.js#L54C1-L54C26

> i also noticed now that lint is quiet there are a few tests that are using `t.diagnostic` and they should prob be removed

Can you clarify this for me? How does the quiet flag affect the `t.diagnostic` invocations?

I set the main lint script to quiet because we have been ignoring warnings anyway. Do we want the noise to return and just keep overlooking it?

2025-01-03 15:19 UTC, bizob2828 commented on test/unit/api/api-instrument-loaded-module.test.js
> -      // eslint-disable-next-line node/no-missing-require
OIC, it doesn't define the `no-missing-require`: https://github.com/neostandard/neostandard/blob/main/lib/configs/base.js#L160

2025-01-03 16:19 UTC, bizob2828 commented on lib/instrumentation/core/http.js
> +    // eslint-disable-next-line n/no-deprecated-api
this is fine but we had this in our rules before to omit this

```sh
    'node/no-deprecated-api': [
      'error',
      {
        ignoreModuleItems: [
          'url.parse'
        ]
      }
    ],
```

2025-01-03 16:24 UTC, bizob2828 commented on lib/custom-events/custom-event-aggregator.js
>      opts.metricNames = opts.metricNames
yea it just looks like it's assigning itself

2025-01-03 16:26 UTC, bizob2828 commented on lib/shim/promise-shim.js
> +        // eslint-disable-next-line sonarjs/no-dead-store
yea i don't get this finally block

2025-01-03 16:27 UTC, bizob2828 commented on lib/shim/message-shim/subscribe-consume.js
> +        // eslint-disable-next-line sonarjs/no-dead-store
i don't really get the reason for the try/finally

2025-01-03 16:28 UTC, bizob2828 commented
> > you removed all the ignoring of the no console and it won't show this as a warning because lint is quiet but not sure if we want to restore those or not.
> 
> Supposedly it was set as "warn" in the original configuration https://github.com/newrelic/eslint-config-newrelic/blob/c5780025fff0c92d6d9012e6132e84fb42ad2459/index.js#L54C1-L54C26
> 
> > i also noticed now that lint is quiet there are a few tests that are using `t.diagnostic` and they should prob be removed
> 
> Can you clarify this for me? How does the quiet flag affect the `t.diagnostic` invocations?
> 
> I set the main lint script to quiet because we have been ignoring warnings anyway. Do we want the noise to return and just keep overlooking it?

We can address the `t.diagnostic` in a different PR. but i'm referring to the noise in the PRs now:

<img width="1174" alt="screenshot 2025-01-03 at 11 27 57 AM" src="https://github.com/user-attachments/assets/17ffcf53-8b25-4e85-987e-f6800c60b3ea" />

2025-01-03 17:13 UTC, jsumners-nr commented on lib/instrumentation/core/http.js
> +    // eslint-disable-next-line n/no-deprecated-api
I missed that.

2025-01-03 17:17 UTC, jsumners-nr commented
> but i'm referring to the noise in the PRs now:

Ah, okay. Those have been there since we migrated to `node:test`, but they were hidden by all of the eslint warnings.

2025-01-03 17:18 UTC, bizob2828 commented
> > but i'm referring to the noise in the PRs now:
> 
> Ah, okay. Those have been there since we migrated to `node:test`, but they were hidden by all of the eslint warnings.

Yep, fixed in #2858

2025-01-03 17:19 UTC, bizob2828 approved these changes
LGTM, we can always tweak this as we go

2025-01-03 17:21 UTC, jsumners-nr commented on lib/shim/message-shim/subscribe-consume.js
> +        // eslint-disable-next-line sonarjs/no-dead-store
If only we could ask the author of the code https://github.com/newrelic/node-newrelic/commit/3d1caaf7d7f7de1c2e139eb7943f557b896fc1e2#diff-c3b4dadcc3b24d7d31b5192193cdb89f33e7c2e9cb2f4b9ddbf7e50067c9240aR192

🤣

2025-01-03 17:32 UTC, bizob2828 commented on lib/shim/message-shim/subscribe-consume.js
> +        // eslint-disable-next-line sonarjs/no-dead-store
nah, i just moved this

2025-01-03 17:32 UTC, bizob2828 submitted a review, later dismissed

2025-01-03 18:29 UTC, bizob2828 approved these changes

2025-01-03 18:30 UTC, merged