Adds create-release workflow and supporting scripts
newrelic/node-newrelic pull request #619
Opened 2021-02-12 23:52 UTC by carlo-808

## Proposed Release Notes
* Adds `Create Release` github actions workflow to create a release for `patch` or `minor` releases
* Updates agent version and adds release tags
## Links
Closes: #585
## Details

2021-02-16 23:11 UTC, michaelgoin requested changes
Since generate-release-notes will be broken, requesting changes on this PR.

Minor comments don't need to be addressed unless desired.

An additional note (can be handled separately): we are getting to enough related scripts that it likely is starting to make sense to organize these into an additional folder at some point.

2021-02-16 23:11 UTC, michaelgoin commented on bin/create-release.js
> +  exec(`npm version ${releaseType} && git push origin ${branch} && git push --tags`, (err, stdout) => {
Not sure what the output looks like but if nothing obvious, we may want to write a message before executing this step.

2021-02-16 23:11 UTC, michaelgoin commented on bin/github.js
> +    this.repoOwner = repoOwner ? repoOwner : 'newrelic'
could be simplified to: `this.repoOwner = repoOwner || 'newrelic'`

2021-02-16 23:11 UTC, michaelgoin commented on bin/github.js
> +class Github {
Given the change to be a class now... I believe generate-release-notes.js will be broken as it has not been updated to use the class.

2021-02-23 19:12 UTC, carlo-808 commented on bin/check-workflow-run.js
> +        results.ci = true
Sounds good, not changing this at this time.

2021-02-23 19:15 UTC, michaelgoin approved these changes

2021-02-23 19:15 UTC, merged