Convert config unit tests
newrelic/node-newrelic pull request #839
Opened 2021-08-17 17:38 UTC by michaelgoin

## Proposed Release Notes

* Converted config unit tests to fully use tap API and extracted related tests into more-specific test files.

## Links

## Details

Apologies for the PR size. On outset, I didn't realize how big the config.test.js file was or I would have approached slightly differently.

Converted all tests from the /config folder in unit tests.

The config.test.js file was massive and thus split out into more targeted test files, where seemed appropriate. This can help speed things up in some cases due to parallelization of test file runs. But mostly, I did this to ease finding of related tests and long-term maintenance.

### main

82675 passing (1m)
33 pending

## this change

82897 passing (1m)
33 pending

Additional assertions mostly due to how tap counts assertions but in some cases additional assertions were added or fixed assertions that were skipped accidentally in the mocha style.

Very little effort was put into validity of tests but rather focused on getting converted for consistency.

I did have to rebase onto the recent Node 16 / tap upgrade changes but didn't have much in the way of conflicts. Mostly just removing serverless_mode feature flag tests again when resolving conflicts. So hopefully didn't end up with any surprises.

2021-08-17 21:00 UTC, bizob2828 requested changes
just a few comments on replacing deprecated uses of
 * `t.deepEqual` w/ `t.same`
 * `t.notThrow` w/ `t.doesNotThrow`

2021-08-17 21:09 UTC, michaelgoin commented on test/unit/config/config-security.test.js
> +    t.deepEqual(config.attributes.exclude, ['request.parameters.*'])
ah yeah, was converted pre-tap migration but i can update.

2021-08-17 21:09 UTC, michaelgoin commented on test/unit/config/collector_hostname.test.js
> +const tap = require('tap')
yeah, i can clean that up.

2021-08-17 21:27 UTC, michaelgoin commented
OK, should have all of the deprecation warnings resolved and renamed the file.

2021-08-18 16:29 UTC, bizob2828 approved these changes

2021-08-18 16:29 UTC, merged